### ISSUE TITLE
CUDA required by PyTorch

### ISSUE THREAD

**Issue by ralf-berger** [ude-soco/elas-official#118]
backend-5-studycompass on startup:

```
Traceback (most recent call last):
  File "/home/app/.venv/lib/python3.10/site-packages/torch/__init__.py", line 168, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/local/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcurand.so.10: cannot open shared object file: No such file or directory
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/app/manage.py", line 22, in <module>
    main()
[...]
  File "/home/app/.venv/lib/python3.10/site-packages/torch/__init__.py", line 154, in _preload_cuda_deps
    raise ValueError(f"{lib_name} not found in the system path {sys.path}")
ValueError: libcublas.so.*[0-9] not found in the system path ['/home/app', '/home/app', '/usr/local/lib/python310.zip', '/usr/local/lib/python3.10', '/usr/local/lib/python3.10/lib-dynload', '/home/app/.venv/lib/python3.10/site-packages']
```

**Comment by shoebjoarder** [comment]
This is due the absence of CUDA libraries `libcublas.so.*[0-9]` required by PyTorch library, which is a dependency of `sentence-transformers` in the 5-studycompass service. For this service, we are not going to use any GPU, so we need to get a CPU only version of PyTorch in order to avoid installing CUDA. To check whether the CPU or GPU version of PyTorch is installed, we can use the following commands in python shell:

```
>>> import torch
>>> print(torch.__version__)
```

**Comment by ralf-berger** [comment]
@shoebjoarder Help required, I can't figure out how to create an updated lock-file (without updating a bunch of other random dependencies).

**Comment by shoebjoarder** [comment]
Seems like the latest version of pytorch is not compatible with python 3.10 and therefore downgraded to the most compatible version `1.11.0` ([source](https://github.com/pytorch/pytorch/issues/66424#issuecomment-1002346504)) . The latest changes are pushed to [19cdcf0](https://github.com/ude-soco/elas-official/pull/146/commits/19cdcf061fbc86140009bc1d5dd283cec0a495f5).

**Comment by ralf-berger** [comment]
backend-5-studycompass confirmed to run in edge deployment. 🥳
