### ISSUE TITLE
Initial project setup

### ISSUE THREAD

**Issue by ralf-berger** [ude-soco/elas-official#12]
- [x] #20
- [x] Dockerfiles
- [x] Compose
- [x] Service configuration
- [x] Dependabot
- [x] Container image registry
- [x] #21
- [x] GitHub description, features, etc.
- [x] GitHub Labels
- [x] GitHub Releases
- [x] CI
- [x] CD

**Comment by shoebjoarder** [comment]
`2-api-gateway` is the only service that is public facing, rest are all backend internal services.
