### ISSUE TITLE
Add MariaDB database

### ISSUE THREAD

**Issue by shoebjoarder** [ude-soco/elas-official#169]
`backend/3-auth` and `backend/4-e3selector` services requires an additional SQL database.

**Comment by shoebjoarder** [comment]
The celery service of the `backend/4-e3selector` should also be able to access the database

**Comment by ralf-berger** [comment]
The associated PR was closed, should this Issue be closed as not planned?

**Comment by shoebjoarder** [comment]
Are we going to request the PR from one of the issue branches that includes MariaDB added to the project? If we close this issue as not planned, should we create another same issue and associate that branch? Since I didn't notice you already created a branch from this issue, that's why I closed the PR... what do you suggest?

**Comment by ralf-berger** [comment]
This issue ~~is~~ was linked to PR #170, which is about a branch [we've both been working on](https://github.com/ude-soco/elas-official/compare/main...issue/169-add-mariadb-databases) (`issue/169-add-mariadb-databases`). I don't understand why the PR is closed if we still want those changes. What other branch is there?

**Comment by shoebjoarder** [comment]
When I created this issue, I created a branch `issue/169-add-mariadb-database` and you also created another branch `issue/169-add-mariadb-databases`. It's true that I worked on your created branch, but it was a slip from my side. I thought I checked out my branch and I started working on it. Never mind, it was just a confusion. Thanks for reopening it.
