### ISSUE TITLE
Fix worker crashing without EUREKA_HOST_NAME

### ISSUE THREAD

**Issue by ralf-berger** [ude-soco/elas-official#95]
### Observed behaviour

backend/e-e3selector crashes when started as Celery worker:

```
Traceback (most recent call last):
[...]
  File "/home/app/server/settings.py", line 53, in <module>
    instance_ip=socket.gethostbyname(EUREKA_HOST_NAME),  # type: ignore
TypeError: gethostbyname() argument 1 must be str, bytes or bytearray, not None
```

### Expected behaviour

backend/e-e3selector should not require Eureka connection data when it's started as Celery worker.

**Comment by shoebjoarder** [comment]
In [dd310ad](https://github.com/ude-soco/elas-official/commit/dd310adb1f2b7396a032c5f19b1332583e737779) an environment variable CELERY_WORKER to the backend/4-e3selector service only for running the Celery worker has been added.
